sudo: false
language: node_js
node_js:
- '9'
cache: yarn
branches:
  only:
    - master
install:
- yarn
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
- yarn start # start a Web server
- sleep 3 # give Web server some time to bind to sockets, etc 
script:
- yarn lint
before_deploy:
- yarn build
- echo "Initializing deployment..."
- cd build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master
after_deploy:
- echo "Deployment complete"
