sudo: false
language: node_js
node_js:
- '9'
cache: yarn
branches:
  only:
    - master
addons:
    apt:
      packages:
        - xvfb
install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
- sh -e /etc/init.d/xvfb start
- yarn
before_script:
- sleep 3
- yarn start &
- sleep 15
script:
- yarn lint
- yarn test:CI
before_deploy:
- yarn build
- echo "Initializing deployment..."
- cd build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master
after_deploy:
- echo "Deployment complete"
